import type { ThemeColors } from './types';

// getDatabase()가 반환하는 화이트리스트 키 (characters, modules 제외 — 별도 블록)
// selectedPersona, characterOrder는 런타임에 접근 가능하나 d.ts에 누락되어 있음
export const ROOT_KEYS: string[] = [
  'enabledModules', 'moduleIntergration', 'pluginV2', 'personas', 'plugins',
  'pluginCustomStorage', 'temperature', 'askRemoval', 'maxContext', 'maxResponse',
  'frequencyPenalty', 'PresensePenalty', 'theme', 'textTheme', 'lineHeight',
  'seperateModelsForAxModels', 'seperateModels', 'customCSS', 'guiHTML',
  'colorSchemeName', 'selectedPersona', 'characterOrder',
];

// getColorScheme() 미구현 버전 대비 fallback — colorscheme.ts의 프리셋 복사
export const PRESET_SCHEMES: Record<string, ThemeColors> = {
  'default':       { bgcolor:'#282a36', darkbg:'#21222c', borderc:'#6272a4', selected:'#44475a', draculared:'#ff5555', textcolor:'#f8f8f2', textcolor2:'#64748b', darkBorderc:'#4b5563', darkbutton:'#374151' },
  'dark':          { bgcolor:'#1a1a1a', darkbg:'#141414', borderc:'#525252', selected:'#3d3d3d', draculared:'#ff5555', textcolor:'#f5f5f5', textcolor2:'#a3a3a3', darkBorderc:'#404040', darkbutton:'#2e2e2e' },
  'light':         { bgcolor:'#ffffff', darkbg:'#f0f0f0', borderc:'#0f172a', selected:'#e0e0e0', draculared:'#ff5555', textcolor:'#0f172a', textcolor2:'#64748b', darkBorderc:'#d1d5db', darkbutton:'#e5e7eb' },
  'cherry':        { bgcolor:'#450a0a', darkbg:'#7f1d1d', borderc:'#ea580c', selected:'#d97706', draculared:'#ff5555', textcolor:'#f8f8f2', textcolor2:'#fca5a5', darkBorderc:'#92400e', darkbutton:'#b45309' },
  'galaxy':        { bgcolor:'#0f172a', darkbg:'#1f2a48', borderc:'#8be9fd', selected:'#457b9d', draculared:'#ff5555', textcolor:'#f8f8f2', textcolor2:'#8be9fd', darkBorderc:'#457b9d', darkbutton:'#1f2a48' },
  'nature':        { bgcolor:'#1b4332', darkbg:'#2d6a4f', borderc:'#a8dadc', selected:'#4d908e', draculared:'#ff5555', textcolor:'#f8f8f2', textcolor2:'#4d908e', darkBorderc:'#457b9d', darkbutton:'#2d6a4f' },
  'realblack':     { bgcolor:'#000000', darkbg:'#000000', borderc:'#6272a4', selected:'#44475a', draculared:'#ff5555', textcolor:'#f8f8f2', textcolor2:'#64748b', darkBorderc:'#4b5563', darkbutton:'#374151' },
  'monokai-light': { bgcolor:'#f8f8f2', darkbg:'#e8e8e3', borderc:'#75715e', selected:'#d8d8d0', draculared:'#f92672', textcolor:'#272822', textcolor2:'#75715e', darkBorderc:'#c0c0b8', darkbutton:'#d0d0c8' },
  'monokai-black': { bgcolor:'#272822', darkbg:'#1e1f1a', borderc:'#75715e', selected:'#3e3d32', draculared:'#f92672', textcolor:'#f8f8f2', textcolor2:'#a6a68a', darkBorderc:'#3e3d32', darkbutton:'#3e3d32' },
  'lite':          { bgcolor:'#1f2937', darkbg:'#1C2533', borderc:'#475569', selected:'#475569', draculared:'#ff5555', textcolor:'#f8f8f2', textcolor2:'#64748b', darkBorderc:'#030712', darkbutton:'#374151' },
};

export const STYLES = [
  '*, *::before, *::after { margin:0; padding:0; box-sizing:border-box; }',
  'html { background:transparent; }',
  'body { font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif; background:rgba(0,0,0,0.55); color:var(--text); line-height:1.6; min-height:100vh; display:flex; align-items:flex-start; justify-content:center; padding:5vh 20px; }',
  '#app { background:var(--bg2); max-width:820px; width:100%; border-radius:12px; border:1px solid var(--border2); box-shadow:0 16px 48px rgba(0,0,0,0.4); padding:24px; max-height:90vh; overflow-y:auto; }',
  '#app { scrollbar-width:none; }',
  '#app::-webkit-scrollbar { display:none; }',
  '.hd { display:flex; justify-content:flex-end; margin-bottom:8px; }',
  '.ha { display:flex; gap:8px; }',
  '.btn { background:var(--btn); border:1px solid var(--border2); color:var(--text); padding:6px 12px; border-radius:6px; cursor:pointer; font-size:.9em; }',
  '.btn:hover { background:var(--border2); }',
  '.bc { color:var(--red); font-size:1.2em; line-height:1; }',
  '.sum { text-align:center; margin-bottom:20px; }',
  '.sum-big { font-size:2em; font-weight:700; }',
  '.sum-label { font-size:.9em; color:var(--text2); margin-top:4px; }',
  '.stack { display:flex; height:28px; border-radius:6px; overflow:hidden; gap:2px; }',
  '.seg { min-width:4px; border-radius:4px; transition:flex .3s; display:flex; align-items:center; justify-content:center; font-size:.75em; font-weight:600; color:#fff; overflow:hidden; white-space:nowrap; }',
  '.stack-leg { display:flex; flex-wrap:wrap; gap:6px 16px; margin-top:10px; font-size:.85em; }',
  '.leg { display:flex; align-items:center; }',
  '.dot { width:10px; height:10px; border-radius:3px; margin-right:6px; flex-shrink:0; }',
  '.c { background:var(--bg); border:1px solid var(--border); border-radius:8px; padding:16px 20px; margin-bottom:12px; }',
  'h2 { font-size:1em; color:var(--text); margin-bottom:10px; }',
  'h3 { font-size:.92em; color:var(--text2); margin-bottom:8px; }',
  '.tw { overflow-x:auto; scrollbar-width:none; }',
  '.tw::-webkit-scrollbar { display:none; }',
  'table { width:100%; min-width:400px; border-collapse:collapse; font-size:.88em; }',
  'th { text-align:left; padding:6px 10px; border-bottom:1px solid var(--border2); color:var(--text2); font-weight:600; }',
  'th.n { text-align:right; }',
  'td { padding:5px 10px; border-bottom:1px solid var(--border); }',
  'tbody tr:hover { background:var(--btn); }',
  '.n { text-align:right; font-variant-numeric:tabular-nums; }',
  'td.bv { position:relative; z-index:0; }',
  'td.bv::before { content:""; position:absolute; right:0; top:2px; bottom:2px; width:var(--w,0%); background:var(--accent); opacity:.3; border-radius:3px; pointer-events:none; z-index:-1; }',
  '.tg { cursor:pointer; user-select:none; }',
  '.tg:hover { color:var(--accent); }',
  '.det-tg { font-size:.92em; color:var(--text2); margin:4px 0 8px; }',
  '.cl { display:none; }',
  '.fn { font-size:.82em; color:var(--text2); text-align:center; margin-top:8px; }',
  '.mt { color:var(--text2); }',
  '.more { text-align:center; color:var(--text2); font-style:italic; }',
  '.loading { text-align:center; padding:80px 20px; font-size:1.1em; color:var(--text2); }',
  '.err { text-align:center; padding:80px 20px; color:var(--red); font-size:1.1em; }',
  '@media(max-width:640px) {',
  '  body { padding:0; background:var(--bg2); }',
  '  #app { border-radius:0; max-height:none; border:none; box-shadow:none; }',
  '  .sum-big { font-size:1.4em; }',
  '  .stack-leg { flex-direction:column; }',
  '  table { font-size:.8em; }',
  '  td,th { padding:4px 6px; }',
  '}',
].join('\n');
